name: Python CI Pipeline

on:
  push:
    branches: [ main ]
  

jobs:
  dev:
    name: app.py 
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run dev script
        run: python app.py

  test:
    name: app1.py 
    runs-on: ubuntu-22.04
    needs: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run test script
        run: python app1.py

  prod:
    name: app2.py
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run prod script
        run: python prod.py
